/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1proyectofinal;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;


/**
 *
 * @author jes_c
 */
public class RegistrosEmp extends javax.swing.JFrame {

    Connection con =null;
    Statement stmt =null;
   String titulos[] = {"Numero Empleado","Nombre","Telefono","Tipo Usuario"};
   String fila[] = new String [3];
   DefaultTableModel modelo;
   String var,var2;
   
    
    
    
    
    public RegistrosEmp() {
        initComponents();
        this.setTitle("Registro Empleados");
        this.setLocation(400, 380);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        txtnombreemp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttelefonoemp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnumeroemp = new javax.swing.JTextField();
        txtpasswordemp = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cons = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmb_tipoUsuario = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 46, 21));

        txtnombreemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreempKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombreemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 240, -1));

        jLabel2.setText("Telefono");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 56, 20));

        txttelefonoemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttelefonoempMouseClicked(evt);
            }
        });
        txttelefonoemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoempKeyTyped(evt);
            }
        });
        getContentPane().add(txttelefonoemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 110, -1));

        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 20));

        jLabel4.setText("Numero de Empleado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));

        txtnumeroemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroempKeyTyped(evt);
            }
        });
        getContentPane().add(txtnumeroemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 110, -1));

        txtpasswordemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordempKeyTyped(evt);
            }
        });
        getContentPane().add(txtpasswordemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 110, -1));

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 89, 29));

        jButton2.setText("Registrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 92, 29));

        cons.setText("Consultar");
        cons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consMouseClicked(evt);
            }
        });
        getContentPane().add(cons, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 93, 29));

        jLabel6.setText("Tipo de Usuario:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 124, 20));

        cmb_tipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Invitado", "Empleado" }));
        getContentPane().add(cmb_tipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 110, 20));

        jButton4.setText("Actualizar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 85, 29));

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 90, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/REGISTROS.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        setBounds(0, 0, 742, 367);
    }// </editor-fold>//GEN-END:initComponents

    public void consulta() {
        String cap="";
        ResultSet rs = null;
        var2 = txtnumeroemp.getText();
        String sql2="Select num_emp, nom_emp,tel_emp, pass_emp, tipo_emp FROM empleados where num_emp = '"+var2+"'";
            
   try { 
       
            String url = "jdbc:mysql://localhost:3306/proyecto?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
            String usuario = "root";
            String contraseña = "JM5038766866"; 
                  
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance(); 
     
     
     con = DriverManager.getConnection(url,usuario,contraseña); 

     if ( con != null ) 
	   System.out.println("Se ha establecido una conexión a la base de datos " + 
	                                       "\n " + url ); 
	  
	stmt = con.createStatement(); 
	rs = stmt.executeQuery(sql2); 
      
	int i=1; 
        if(!rs.next())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontro ningun registro","AVISO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
            rs = stmt.executeQuery(sql2);
	   while ( rs.next() ) { 
               
	           String id = rs.getString("num_emp"); 
	           String inom = rs.getString("nom_emp"); 
	           String itel = rs.getString("tel_emp"); 
                   String ipass = rs.getString("pass_emp");
                   String itipo = rs.getString("tipo_emp");
	           System.out.println("Sitio Web "+ (i++) + ":\n" 
	                     
                           + id + "\n"
                           + inom + "\n"  
                           + itel + "\n"
                           + ipass + "\n"
                           + itipo + "\n\n" ); 
                   
                   txtnumeroemp.setText(id);
                   txtnombreemp.setText(inom);
                   txttelefonoemp.setText(itel);
                   txtpasswordemp.setText(ipass);
                   cmb_tipoUsuario.setSelectedItem(itipo);
                  
	         } 
	        } 
                  catch( SQLException ex ) { 
                      ex.printStackTrace(); 
	                  } catch (InstantiationException | IllegalAccessException | ClassNotFoundException ex) {
            Logger.getLogger(RegistrosEmp.class.getName()).log(Level.SEVERE, null, ex);
        } 
	  
	              finally { 
	                  if ( rs != null ) { 
	                      try    { 
	                          rs.close(); 
	                      } catch( SQLException ex ) { 
	                          System.out.println( ex.getMessage()); 
	                          ex.printStackTrace(); 
	                      } 
	                  } 
	                  if ( stmt != null ) { 
	                      try    { 
	                          stmt.close(); 
	                      } catch( SQLException ex ) { 
	                          System.out.println( ex.getMessage()); 
	                          ex.printStackTrace(); 
	                      } 
	                  } 
	                  if ( con != null ) { 
	                      try    { 
	                          con.close(); 
	                      } catch( SQLException ex ) { 
	                          System.out.println( ex.getMessage()); 
	                          ex.printStackTrace(); 
         } 
       }
     }    
    }

   public void actualizar() {
        
        String cadena1,cadena2,cadena3,cadena4,cadena5;
     
       cadena1 = txtnumeroemp.getText();
       cadena2 = txtnombreemp.getText();
       cadena3 = txttelefonoemp.getText();
       cadena4 = txtpasswordemp.getText();
       cadena5 = cmb_tipoUsuario.getSelectedItem().toString();
     
    
     if (txtnombreemp.getText().equals("")) {
         
         javax.swing.JOptionPane.showMessageDialog(this,"1-. Consulte el numero del empleado\n 2-. Actualice el dato deseado en el campo correspondiente","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
     }
     else {   
     
     try { 
            String url = "jdbc:mysql://localhost:3306/proyecto?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
            String usuario = "root";
            String contraseña = "JM5038766866"; 
                  
                  Class.forName("com.mysql.cj.jdbc.Driver").newInstance(); 
                  con = DriverManager.getConnection(url,usuario,contraseña); 
                  if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
                  stmt = con.createStatement();
                  ResultSet rs = stmt.executeQuery("select* from empleados where num_emp = '"+txtnumeroemp.getText()+"'");
                  if(rs.next()==false)
                  {
                      javax.swing.JOptionPane.showMessageDialog(this,"No existe un registro con ese numero de empleado!","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                  }
                  else
                  {
                  stmt.executeUpdate("update ignore empleados set num_emp= '"+cadena1+"' , nom_emp = '"+cadena2+"',tel_emp = '"+cadena3+"', pass_emp = '"+cadena4+"', tipo_emp = '"+cadena5+"' where num_emp = '"+txtnumeroemp.getText()+"' "); 
                  System.out.println("Los valores han sido Actualizados"); 
                  javax.swing.JOptionPane.showMessageDialog(this,"Actualizado correctamente!","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                  }
                 
                  } 
                  catch( SQLException e ) { 
                      e.printStackTrace(); 
                  } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(RegistrosEmp.class.getName()).log(Level.SEVERE, null, ex);
        } 
  
              finally { 
                  if ( con != null ) { 
                      try    { 
                          con.close(); 
                          stmt.close(); 
                      } catch( Exception e ) { 
                          System.out.println( e.getMessage()); 
                      } 
                  } 
     }
     
     } 
        this.txtnumeroemp.setText("");
        this.txtnombreemp.setText("");
        this.txttelefonoemp.setText("");
        this.txtpasswordemp.setText("");
        Empleados.refresh.doClick();
    }
   
   public void registrar()
   {
       String cadena2, cadena3, cadena4,cadena5,cadena6;    
      cadena2 = txtnumeroemp.getText();
      cadena3 = txtnombreemp.getText();
      cadena4 = txttelefonoemp.getText();
      cadena5 = txtpasswordemp.getText();
      cadena6 = cmb_tipoUsuario.getSelectedItem().toString();
              
      
     if (txtnombreemp.getText().equals("") || (txttelefonoemp.getText().equals("")) || (txtnumeroemp.getText().equals("")) || (txtpasswordemp.getText().equals("")) ) {
            
     javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
     txtnombreemp.requestFocus();
     }
     
     else {
        try {
           
            String url = "jdbc:mysql://localhost:3306/proyecto?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
            String usuario = "root";
            String contraseña = "JM5038766866"; 
            
             Class.forName("com.mysql.cj.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
                  stmt = con.createStatement(); 
                  ResultSet rs = stmt.executeQuery("select* from empleados");
                  
                            if(rs.next()==false)
                      {
                              stmt.executeUpdate("INSERT INTO empleados(`num_emp`, `nom_emp`, `tel_emp`, `pass_emp`, `tipo_emp`) VALUES('"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"','"+cadena6+"')");
                              System.out.println("Los valores han sido agregados a la base de datos");
                              javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                      }
                      else
                      {
                          rs = stmt.executeQuery("Select* from empleados");
                      if(rs.next()==true)
                      {
                          rs = stmt.executeQuery("select* from empleados where num_emp = '"+cadena2+"'");
                          if(rs.next()==true)
                          {
                              javax.swing.JOptionPane.showMessageDialog(this,"Ya se registro este numero!\n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                          }
                          else
                          {
                              stmt.executeUpdate("INSERT INTO empleados(`num_emp`, `nom_emp`, `tel_emp`, `pass_emp`, `tipo_emp`) VALUES('"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"','"+cadena6+"')");
                              System.out.println("Los valores han sido agregados a la base de datos");
                              javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                          }
                      }
                      }
        } catch (InstantiationException | IllegalAccessException | ClassNotFoundException | SQLException ex) {
           Logger.getLogger(RegistrosEmp.class.getName()).log(Level.SEVERE, null, ex);
       }  
        
        finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( SQLException e ) { 
                         System.out.println( e.getMessage());
                }
            }
        }
         
        }
        this.txtnumeroemp.setText("");
        this.txtnombreemp.setText("");
        this.txttelefonoemp.setText("");
        this.txtpasswordemp.setText("");  
        Empleados.refresh.doClick();
      
      
   }
   public void  limpiar ()
   {
       this.txtnumeroemp.setText("");
         this.txtnombreemp.setText("");
        this.txttelefonoemp.setText("");
        this.txtpasswordemp.setText(""); 
   }
      
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
                    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void txtnombreempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreempKeyTyped
              char c = evt.getKeyChar();
        int numerocaracteres=45;

        if(txtnombreemp.getText().length() >= numerocaracteres)
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se pueden 45 digitos en el nombre");
        }
        if((c<'a' || c>'z') && (c<'A' || c> 'Z') && (c<' ' || c> ' ') ) evt.consume();      
    }//GEN-LAST:event_txtnombreempKeyTyped

    private void txttelefonoempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttelefonoempMouseClicked

    }//GEN-LAST:event_txttelefonoempMouseClicked

    private void txttelefonoempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoempKeyTyped
        char c = evt.getKeyChar();
         int numerocaracteres=10;
        
        if(txttelefonoemp.getText().length() >= numerocaracteres)
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se pueden 10 digitos en el telefono");
        }
        
        if((c<'0' || c> '9')) evt.consume();   
    }//GEN-LAST:event_txttelefonoempKeyTyped

    private void txtnumeroempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroempKeyTyped
        char c = evt.getKeyChar();
        int numerocaracteres=6;
        
        if(txtnumeroemp.getText().length() >= numerocaracteres)
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se pueden 6 digitos en el numero de empleado");
        }
        
        if((c<'0' || c> '9')) evt.consume(); 
    }//GEN-LAST:event_txtnumeroempKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       registrar();      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void consMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consMouseClicked
       consulta();           
    }//GEN-LAST:event_consMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
       actualizar();            
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       limpiar();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtpasswordempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordempKeyTyped
            char c = evt.getKeyChar();
        int numerocaracteres=45;

        if(txtpasswordemp.getText().length() >= numerocaracteres)
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se pueden 45 digitos en la membresía");
        }
        if((c<'a' || c>'z') && (c<'A' || c> 'Z') && (c<' ' || c> ' ') && (c<'0' || c> '9')) evt.consume();
    }//GEN-LAST:event_txtpasswordempKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrosEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrosEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrosEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrosEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrosEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_tipoUsuario;
    public static javax.swing.JButton cons;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtnombreemp;
    public static javax.swing.JTextField txtnumeroemp;
    private javax.swing.JPasswordField txtpasswordemp;
    private javax.swing.JTextField txttelefonoemp;
    // End of variables declaration//GEN-END:variables
}
